# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.plugin import BasePlugin
import requests, random

class PigHubBot(BasePlugin):

    def __init__(self):
        super().__init__()

    async def initialize(self) -> None:
        # 初始化Pig Hub API
        self.pighub_url = "https://pighub.top"
        self.headers = {
            "Content-Type": "application/json;charset=utf-8",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
        }
        self.images = await self.all_images()
    
    async def all_images(self):
        api = "/api/all-images"
        try:
            response = requests.get(self.pighub_url + api, headers=self.headers)
            if response.ok:
                return response.json()
            else:
                print(response)
                return None
        except Exception as e:
            print(e)
            return None
        
    async def random_image(self):
        body = self.images
        if body:
            list = body["images"]
            data = random.choice(list)
            filename = data["filename"]
            return self.pighub_url + "/data/" + filename
        else:
            return None
        
    async def random_filtered_image(self, keyword):
        body = self.images
        if body:
            image_list = body["images"]
            filtered_list = list(filter(lambda x: 
                                        keyword.lower() in x["title"].lower() or
                                        keyword.lower() in x["filename"].lower() or
                                        keyword.lower() in x["duration"].lower(), image_list))
            if filtered_list:
                data = random.choice(filtered_list)
                filename = data["filename"]
                return self.pighub_url + "/data/" + filename
            else:
                return None
        else:
            return None