# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.plugin import BasePlugin
import requests, random
from thefuzz import process

class PigHubBot(BasePlugin):

    def __init__(self):
        super().__init__()

    async def initialize(self) -> None:
        # 初始化Pig Hub API
        self.pighub_url = "https://pighub.top"
        self.headers = {
            "Content-Type": "application/json;charset=utf-8",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
        }
    
    async def all_images(self):
        api = "/api/all-images"
        try:
            response = requests.get(self.pighub_url + api, headers=self.headers)
            if response.ok:
                return response.json()
            else:
                print(response)
                return None
        except Exception as e:
            print(e)
            return None
        
    async def random_image(self):
        body = await self.all_images()
        if body:
            list = body["images"]
            data = random.choice(list)
            filename = data["filename"]
            return self.pighub_url + "/data/" + filename
        else:
            return None
        
    async def random_filtered_image(self, keyword):
        body = await self.all_images()
        if body:
            image_list = body["images"]
            best_match = process.extractOne(keyword, image_list)
            image, _ = best_match
            if image:
                filename = image["filename"]
                return self.pighub_url + "/data/" + filename
            else:
                return None
        else:
            return None