apiVersion: v1
kind: Plugin
metadata:
  author: Garrise
  name: PigHubBot
  repository: ''
  version: 0.1.0
  description:
    en_US: ''
    zh_Hans: ''
  label:
    en_US: PigHubBot
    zh_Hans: PigHubBot
  icon: assets/icon.svg
spec:
  config: []
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: PigHubBot
